### ISSUE TITLE
2 line ellipsis not working

### ISSUE THREAD

**Issue by cwilvx** [wobsoriano/vue-wrap-balancer#8]
@wobsoriano 

Thanks a lot for this module. It works perfectly.

I'm trying to ellipsize a heading that overflows 2 lines. I have written this CSS class for normal heading.

```css
.ellip2 {
  word-wrap: anywhere;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
How do I use the class or any other means to ellipsize headings overflowing 2 lines and balance those that don't? I've tried adding the class at various elements inside and outside the element with the directive but none works.
